### ISSUE TITLE
Got LoadError trying to load rake

### ISSUE THREAD

**Issue by Shmuwol** [learn-co-curriculum/activerecord-associations-intro#15]
```bash
[00:03:42] (master) activerecord-associations-intro-v-000
// ♥ rake db:migrate
rake aborted!
LoadError: cannot load such file -- rake
/Users/shmullywolfson/Development/code/activerecord-associations-intro-v-000/config/environment.rb:5:in `require'
/Users/shmullywolfson/Development/code/activerecord-associations-intro-v-000/config/environment.rb:5:in `<top (required)>'
/Users/shmullywolfson/Development/code/activerecord-associations-intro-v-000/Rakefile:3:in `require_relative'
/Users/shmullywolfson/Development/code/activerecord-associations-intro-v-000/Rakefile:3:in `block in <top (required)>'
/Users/shmullywolfson/.rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/shmullywolfson/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/shmullywolfson/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

got it to work after deleting line 5 `require 'rake'` of `environment.rb`

**Comment by pletcher** [comment]
This was a repo-sync issue; it was fixed manually with https://github.com/learn-co-students/activerecord-associations-intro-v-000/commit/e4f3c52e1686bd1285b592e0523f2264819df892
